library(tidyverse)
library(ggtext)
library(shadowtext)
library(here)

base_path <- here("2024", "21")


#' Source: Umweltbundesamt
#' https://www.umweltbundesamt.de/bild/vermiedene-treibhausgas-emissionen-durch-die-0

# Download report Excel file
report_url <- "https://www.umweltbundesamt.de/sites/default/files/medien/384/bilder/dateien/de-en_indikator_klim-04_vermied-treibhausgase-ee_2024-04-02.xlsx"
report_file <- here(base_path, "de-en_indikator_klim-04_vermied-treibhausgase-ee_2024-04-02.xlsx")
download.file(report_url, destfile = report_file)

column_names <- c("x1", "year", "electricity", "heat", "transportation", "total")

report <- readxl::read_excel(
  report_file, sheet = "Daten", skip = 14, col_names = column_names, na = "-") |> 
  select(-x1) |> 
  na.omit()  |> 
  filter(year >= 2000)
glimpse(report)

report_long <- report |> 
  pivot_longer(cols = c(electricity, heat, transportation),
               names_to = "area", values_to = "emissions_saved",
               names_transform = str_to_title)


# Custom theme
colors <- c("#EBEAEC", "#FFFFFF")
gradient_fill <- grid::linearGradient(colors, group = FALSE)
theme_set(
  theme_minimal(base_family = "Libre Franklin") +
    theme(
      plot.background = element_rect(color = gradient_fill, fill = gradient_fill),
      text = element_text(color = "#090909"),
      axis.title = element_blank(),
      axis.text = element_text(family = "Source Code Pro", size = 6),
      axis.text.y = element_text(),
      axis.line.x = element_line(),
      plot.title = element_markdown(
        color = "grey8", lineheight = 1.2,
        family = "Libre Franklin SemiBold", hjust = 0, size = 14,
        margin = margin(t = 4, b = 4)),
      plot.title.position = "plot",
      plot.subtitle = element_textbox(
        hjust = 1, halign = 1, color = "grey35", size = 8, width = 1, lineheight = 1.2,
        margin = margin(b = 2)),
      plot.caption = element_textbox(
        width = 1, hjust = 0, lineheight = 1.1, size = 6),
      plot.margin = margin(t = 4, l = 12, b = 2, r = 4),
      legend.position = "top",
      panel.grid.major.x = element_blank(),
      panel.grid.minor.x = element_blank(),
      panel.grid.major.y = element_line(color = "grey70", linewidth = 0.15),
      panel.grid.minor.y = element_line(color = "grey70", linewidth = 0.05),
      strip.text = element_text(
        family = "Libre Franklin Medium", size = 7, color = "grey25",
        margin = margin(t = -1, b = 1)),
      panel.spacing.x = unit(2, "mm") 
    )
)


report_long |> 
  mutate(
    emissions_saved = emissions_saved / 1000,
    area = fct_reorder(area, emissions_saved)) |> 
  arrange(year, desc(area)) |>
  ggplot(aes(year, emissions_saved, fill = area)) +
  geom_area(alpha = 0.9) +
  geom_shadowtext(
    data = ~subset(., year == max(year)),
    aes(
      year - 0.25, 
      cumsum(lag(emissions_saved, default = 0)) + emissions_saved / 2,
      label = area, group = area),
    # position = "stack",
    hjust = 1, family = "Libre Franklin Medium", size = 2.5, # nudge_x = -0.25,
    color = "white", bg.color = "black"
  ) +
  scale_x_continuous(
    breaks = seq(2000, 2050, 2), expand = c(0, 0)) +
  scale_y_continuous(
    position = "right",
    breaks = seq(0, 1000, 50), expand = c(0, 0)) +
  scale_fill_manual(values = c("#E6A654", "#978EBF", "#4F2983")) +
  coord_cartesian(ylim = c(0, 250), clip = "off") +
  guides(fill = "none") +
  labs(
    title = "Avoided greenhouse gas emission by the use<br>of renewable energies
    in Germany",
    subtitle = "<br> <span style='font-size:7pt;font-family:\"Libre Franklin SemiBold\"'>
    Billion tons CO<sub>2</sub> equivalents \U2193</span>",
    caption = "Note: The calculation of the indicator assumes that the energy
    currently generated by renewable energy sources no longer needs to be
    provided by a fossil energy mix.<br>
    Source: German Environment Agency (UBA). Visualization: Ansgar Wolsing"
  )
ggsave(here(base_path, "21-green-energy-emissions-saved.png"), width = 5, height = 5)
